services:
  db:
    image: postgres:18.1
    container_name: bank_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-dev:
    image: maven:3.9.12-amazoncorretto-17
    container_name: bank_app_dev
    command: mvn -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" spring-boot:run
    working_dir: /workspace
    volumes:
      - ./:/workspace               
      - maven-repo:/root/.m2  
      - ./logs:/workspace/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=dev
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_JWT_EXPIRATION=${APP_JWT_EXPIRATION}
      - APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
  maven-repo: