openapi: 3.1.0
info:
  title: REST API Системы управления банковскими картами
  version: v1
servers:
- url: http://localhost:8080
  description: Generated server url
security:
- bearerAuth: []
tags:
- name: Администратор
  description: Методы доступные только админу
paths:
  /api/v1/bank-cards/{cardId}/request-block/:
    put:
      tags:
      - Пользовательские методы для карт
      summary: Запрос на блокировку карты
      operationId: requestBlockMyCard
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDto"
  /api/v1/bank-cards/transfer:
    put:
      tags:
      - Пользовательские методы для карт
      summary: Перевод с одной на другую карту
      operationId: transfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransferRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TransferResponseDto"
  /api/v1/admin/users/{id}:
    get:
      tags:
      - Администратор
      summary: Получить пользователя
      operationId: getUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
    put:
      tags:
      - Администратор
      summary: Редактировать пользователя
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
    delete:
      tags:
      - Администратор
      summary: Удалить пользователя
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/admin/bank-cards/{cardId}:
    put:
      tags:
      - Администратор
      summary: Редактирование карты
      operationId: updateCard
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankCardUpdateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDto"
    delete:
      tags:
      - Администратор
      summary: Удалить карту
      operationId: deleteCard
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
  /api/v1/admin/bank-cards/confirm-block/{cardId}:
    put:
      tags:
      - Администратор
      summary: Блокировка карты
      operationId: confirmBlock
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDto"
  /api/v1/admin/bank-cards/activate/{cardId}:
    put:
      tags:
      - Администратор
      summary: Активировать карту
      operationId: activateCard
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDto"
  /api/v1/auth:
    post:
      tags:
      - Авторизация
      summary: Авторизация по JWT Bearer
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthResponseDto"
      security:
      - none: []
  /api/v1/admin/users:
    get:
      tags:
      - Администратор
      summary: Список всех пользователей
      operationId: getUsers
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageUserDto"
    post:
      tags:
      - Администратор
      summary: Регистрация пользователя
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserStoreDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
  /api/v1/admin/bank-cards/{ownerUserId}:
    post:
      tags:
      - Администратор
      summary: Создать карту
      operationId: createCard
      parameters:
      - name: ownerUserId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDto"
  /api/v1/bank-cards:
    get:
      tags:
      - Пользовательские методы для карт
      summary: Список моих карт
      operationId: getMyCards
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      - name: cardNumberLast4
        in: query
        required: false
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageBankCardDto"
  /api/v1/bank-cards/{cardId}/details:
    get:
      tags:
      - Пользовательские методы для карт
      summary: Получить скрытые данные моей карты
      operationId: getFullDetails
      parameters:
      - name: cardId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BankCardDetailsDto"
  /api/v1/admin/bank-cards:
    get:
      tags:
      - Администратор
      summary: Поиск по всем картам
      operationId: getCards
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      - name: cardNumberLast4
        in: query
        required: false
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageBankCardDto"
  /api/v1/admin/bank-cards/with-block-request:
    get:
      tags:
      - Администратор
      summary: Список карт с запросом на блокировку
      operationId: cardsWithBlockRequest
      parameters:
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      - name: cardNumberLast4
        in: query
        required: false
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageBankCardDto"
components:
  schemas:
    BankCardDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cardNumber:
          type: string
        expirationDate:
          type: string
          example: 2025-03
        status:
          type: string
          enum:
          - ACTIVE
          - BLOCKED
          - EXPIRED
        balance:
          type: number
        cardHolderName:
          type: string
    TransferRequestDto:
      type: object
      properties:
        fromCardNumber:
          type: string
          minLength: 1
        toCardNumber:
          type: string
          minLength: 1
        amount:
          type: number
          minimum: 0.01
      required:
      - amount
    TransferResponseDto:
      type: object
      properties:
        fromCard:
          $ref: "#/components/schemas/BankCardDto"
        toCard:
          $ref: "#/components/schemas/BankCardDto"
    UserUpdateRequestDto:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
        role:
          type: string
          enum:
          - ADMIN
          - USER
        cardHolderName:
          type: string
          minLength: 1
      required:
      - role
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        cardHolderName:
          type: string
        role:
          type: string
          enum:
          - ADMIN
          - USER
    BankCardUpdateDto:
      type: object
      properties:
        cardNumber:
          type: string
        expirationDate:
          type: string
          example: 2025-03
        userId:
          type: integer
          format: int64
        balance:
          type: number
      required:
      - balance
      - expirationDate
      - userId
    AuthRequestDto:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponseDto:
      type: object
      properties:
        accessToken:
          type: string
    UserStoreDto:
      type: object
      properties:
        username:
          type: string
          minLength: 1
        cardHolderName:
          type: string
          minLength: 1
        role:
          type: string
          enum:
          - ADMIN
          - USER
        password:
          type: string
          minLength: 1
      required:
      - role
    Pageable:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 0
        size:
          type: integer
          format: int32
          minimum: 1
        sort:
          type: array
          items:
            type: string
    PageBankCardDto:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/BankCardDto"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        paged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        unpaged:
          type: boolean
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
    SortObject:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean
    BankCardDetailsDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        cardNumber:
          type: string
        expirationDate:
          type: string
          example: 2025-03
        status:
          type: string
          enum:
          - ACTIVE
          - BLOCKED
          - EXPIRED
        balance:
          type: number
        cardHolderName:
          type: string
    PageUserDto:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/UserDto"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      in: header
      scheme: bearer
      bearerFormat: JWT
